language: julia
os:
  - linux
julia:
  - 1.2.0
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2.0
      os: linux
      env:
        DOCUMENTER_DEBUG: true
        GITHUB_TOKEN: ${{ secrets.DOCUMENTER_TOKEN }}
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
